apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-03fe69956a3a7bfb6

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim
spec:
  storageClassName: ""
  volumeName: ebs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
  labels:
    project: expense
    purpose: ebs-static
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-static-claim
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  selector:
    project: expense
    purpose: ebs-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
