apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-dynamic
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    project: expense
    purpose: ebs-dynamic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-claim
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  selector:
    project: expense
    purpose: ebs-dynamic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
