apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
