apiVersion: v1
kind: Pod
metadata:
  name: nginx-multi-container
  labels:
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
    - name: almalinux
      image: almalinux
      command: ["sleep", "2000"]
