---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  github_url: "https://github.com/harsha-commit/expense-k8s.git"

---
apiVersion: v1
kind: Pod
metadata:
  name: configmappod
  labels:
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      envFrom:
        - configMapRef:
            name: configmap
