---
apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi

---
apiVersion: v1
kind: Pod
metadata:
  name: secretspod
spec:
  containers:
  - name: nginx
      image: nginx:1.14.2
    envFrom:
    - secretRef:
        name: secret
