apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      env:
        - name: USER_GREETING
          value: "Hello from the environment"
