---
apiVersion: v1
kind: Pod
metadata:
  name: nodeportpod
  labels:
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
