apiVersion: v1
kind: Pod
metadata:
  name: loadbalancerpod
  labels:
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32760
